### ISSUE TITLE
Carthage cannot be used to install Texture.

### ISSUE THREAD

**Issue by GG526** [TextureGroup/Texture#1074]
I used ```github "texturegroup/texture"```'in the Cartfile .
execute ``` Carthage update texture -platform iOS```  .
Stop at```Cloning libwebp``` and have been using a lot of my computer memory.

**Comment by GG526** [comment]
The ```Cloning libwebp```is repeated

**Comment by GG526** [comment]
<img width="215" alt="2018-08-14 12 40 12" src="https://user-images.githubusercontent.com/11623029/44046117-21f3e438-9f5d-11e8-9c7d-f9fae50bf5ef.png">
<img width="307" alt="2018-08-14 12 39 42" src="https://user-images.githubusercontent.com/11623029/44046135-298a714e-9f5d-11e8-8d7c-6a683afd26c7.png">

**Comment by maskzh** [comment]
@GG526 The **libwebp** address is https://chromium.googlesource.com/webm/libwebp，you need cross the wall。

**Comment by GG526** [comment]
@maskzh  I'm already outside the wall.

**Comment by maskzh** [comment]
@GG526 I have same issue.
`git clone` may not be proxy and I resolved by config git like this

```sh
git config –global http.proxy ‘socks5://127.0.0.1:1080’
```

**Comment by GG526** [comment]
@maskzh Do you use Carthage？I set the proxy and it still doesn't work.

**Comment by GG526** [comment]
@maskzh 
 Thank you very much! I have time to deal with it today and finally found out that my proxy port is something else. Now it's working.
